# Generated by Django 4.2 on 2023-04-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_nominationcategory_options_nominee'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
